#!/usr/bin/env node
/**
 * Regenerate the committed, byte-reproducible examples/ artifacts — the
 * from-scratch reproducibility evidence a third party (and test/w2-examples.test.ts)
 * checks. Running this MUST be idempotent: it rewrites identical bytes every time.
 *
 * WHY this is byte-stable across machines and runs:
 *   - Ed25519 (RFC 8032) signing is DETERMINISTIC — the same private key over the
 *     same message bytes yields the same 64-byte signature, with no randomness.
 *   - The signed message is the RFC 8785 (JCS) canonical form of the envelope, a
 *     single canonical byte string independent of insertion order.
 *   - The two non-deterministic envelope fields (decision_id's UUID and
 *     decision_timestamp) are pinned by fixedEnvelopeDeps.
 *   - The signing key is IMPORTED from the committed examples/issuer.demo.jwk.json,
 *     never generated here. generateSigningKey() would mint a fresh key each run
 *     and the committed .jws would no longer match — defeating the whole example.
 *
 * This file owns ALL derived example artifacts so none of them can drift:
 *   examples/jwks.json   — the PUBLIC JWKS for the demo key (no private `d`)
 *   examples/pack.json   — a copy of rule-packs/shariah/0.1.0.json (re-hashable)
 *   examples/casino-hotel.evidence.jws — the signed DENY evidence artifact
 * It does NOT (re)generate examples/issuer.demo.jwk.json — that throwaway demo
 * private key is committed once and is the fixed anchor of reproducibility.
 *
 * Usage:  node --experimental-strip-types --no-warnings scripts/build-example.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  buildJwks,
  importPrivateJwk,
  type PrivateJwk,
  type SigningKey,
} from "../src/crypto/keys.ts";
import {
  buildEnvelope,
  signEnvelope,
  type EnvelopeDeps,
} from "../src/evidence/envelope.ts";
import { evaluate } from "../src/rules/evaluator.ts";
import { loadRulePack, type LoadedRulePack } from "../src/rules/loader.ts";
import { fixedEnvelopeDeps } from "../test/fixtures/deps.ts";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
export const EXAMPLES_DIR = join(repoRoot, "examples");
export const DEMO_KEY_PATH = join(EXAMPLES_DIR, "issuer.demo.jwk.json");
export const SOURCE_PACK_PATH = join(
  repoRoot,
  "rule-packs",
  "shariah",
  "0.1.0.json",
);
export const EXAMPLE_JWKS_PATH = join(EXAMPLES_DIR, "jwks.json");
export const EXAMPLE_PACK_PATH = join(EXAMPLES_DIR, "pack.json");
export const EXAMPLE_EVIDENCE_PATH = join(
  EXAMPLES_DIR,
  "casino-hotel.evidence.jws",
);

/**
 * UC1 demo intent: an agent books a "casino-hotel" whose merchant attributes
 * flag gambling → MAYSIR-ATTR matches → decision "deny". A GENERIC synthetic
 * label and synthetic data only (no PII, no real merchant). Frozen so the
 * canonical intent bytes — and therefore intent_hash and the signature — are
 * identical to the literal asserted in test/w2-examples.test.ts.
 */
export const casinoHotelIntent: Record<string, unknown> = {
  profile: "shariah-v0.1",
  merchant: {
    name: "casino-hotel",
    mcc: "7011",
    country: "GB",
    attributes: ["casino", "gambling"],
  },
  amount: { value: 389.99, currency: "GBP" },
};

/** Load + import the committed throwaway demo signing key (never generate one). */
export function loadDemoSigningKey(): SigningKey {
  const jwk = JSON.parse(readFileSync(DEMO_KEY_PATH, "utf8")) as PrivateJwk;
  return importPrivateJwk(jwk);
}

/** Load the source rule pack the example is decided against. */
export function loadExamplePack(): LoadedRulePack {
  return loadRulePack(readFileSync(SOURCE_PACK_PATH, "utf8"));
}

/**
 * The SINGLE builder of the example evidence artifact, shared verbatim by this
 * generator and test/w2-examples.test.ts so the regenerated bytes and the
 * committed file can never drift. Pure given (key, pack, deps): no I/O, no
 * randomness, no clock — every input is injected.
 */
export function buildExampleEvidence(
  key: SigningKey,
  loadedPack: LoadedRulePack,
  deps: EnvelopeDeps = fixedEnvelopeDeps,
): string {
  const evaluation = evaluate(casinoHotelIntent, loadedPack.pack);
  const envelope = buildEnvelope(
    casinoHotelIntent,
    evaluation,
    loadedPack,
    deps,
  );
  return signEnvelope(envelope, key);
}

/**
 * Regenerate every DERIVED example file from the committed demo key + source
 * pack. Idempotent: identical bytes each run.
 *
 * The .jws is written with NO trailing newline. It is a single-line base64url
 * string with no internal newlines, so omitting the newline keeps the file
 * byte-identical to the in-memory artifact (and immune to .gitattributes
 * eol=lf normalization, which only touches lines). The .json files are always
 * JSON-parsed by consumers, so their trailing newline is irrelevant.
 */
export function regenerateExamples(): {
  evidence: string;
  decision: string;
  rulePackHash: string;
} {
  const key = loadDemoSigningKey();
  const loadedPack = loadExamplePack();

  // PUBLIC JWKS only — buildJwks copies the public JWK, which carries no `d`.
  writeFileSync(
    EXAMPLE_JWKS_PATH,
    JSON.stringify(buildJwks([key.publicJwk]), null, 2) + "\n",
    "utf8",
  );

  // A verbatim copy of the source pack so an outsider can re-hash it offline.
  // The offline verifier canonicalizes whatever pack JSON it is handed, so a
  // pretty-printed copy still recomputes the same rule_pack_hash.
  writeFileSync(EXAMPLE_PACK_PATH, readFileSync(SOURCE_PACK_PATH, "utf8"), "utf8");

  const evidence = buildExampleEvidence(key, loadedPack);
  writeFileSync(EXAMPLE_EVIDENCE_PATH, evidence, "utf8"); // no trailing newline

  const evaluation = evaluate(casinoHotelIntent, loadedPack.pack);
  return {
    evidence,
    decision: evaluation.decision,
    rulePackHash: loadedPack.hash,
  };
}

function main(): void {
  const { decision, rulePackHash } = regenerateExamples();
  console.log("Regenerated examples/ (byte-reproducible):");
  console.log(`  examples/jwks.json`);
  console.log(`  examples/pack.json`);
  console.log(`  examples/casino-hotel.evidence.jws  → decision "${decision}"`);
  console.log(`  rule_pack_hash: ${rulePackHash}`);
  console.log(
    "  UNCERTIFIED — synthetic demo rule pack; not a fatwa / not certified / not production advice.",
  );
}

// Mirror verify.mjs's isMain guard (NOT replay.ts's unconditional main()): the
// pure builder above is importable by the test without side effects, and the
// file-writing main() runs only when this script is the entrypoint.
const isMain =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) main();
